<?

$title = 'Add new point';
$this->headTitle($title);
?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
/**@var $form Point\Form\PointForm  */
$form->setAttribute('action', $this->url('point', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('trade_id'));
echo $this->formRow($form->get('address'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();