<?php
$title = 'My points';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('point', array('action'=>'add'));?>">Add new album</a>
</p>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjWX6SIq5N61AtHLPrvpEJ4Y_0PaEVGrM">
</script>
<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            center: new google.maps.LatLng(55.750188, 37.624451),
            zoom: 10,
            disableDoubleClickZoom: true
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
        window.listener = google.maps.event.addListener(map, 'dblclick', function (event) {
            if(confirm('add marker?')){
                placeMarker(event.latLng);
            }
            event.stop();
            return false;
        });
        function placeMarker(location) {
            $.post(
                '/point/add',
                {latitude: location.lat(), longitude: location.lng()},
                function(response){
                    var marker = new google.maps.Marker({
                        position: location,
                        map: map
                    });
                }
            );
        }
        <?php foreach ($points as $point) : ?>
        <?php /**@var $point \Point\Model\Point */ ?>

        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(<?php echo (float)$point->getLatitude() ?>, <?php echo (float)$point->getLongitude() ?>),
            map: map,
        });
        <?php endforeach; ?>
        return map;
    }
    var map = google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="map-canvas"></div>
<style type="text/css">
    html { height: 100% }
    body { height: 100%; margin: 0; padding: 0 }
    #map-canvas { height: 600px; width: 1200px;}
</style>
